[workspace]
resolver = "2"
members = [
    "crates/rainbeam",
    "crates/authbeam",
    "crates/databeam",
    "crates/shared",
    "crates/rainbeam-core",
    "crates/citrus",
    "crates/langbeam",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
# panic = "abort"
panic = "unwind"
strip = true
