[workspace]
resolver = "2"
members = [
  "crates/rainbeam",
  "crates/authbeam",
  "crates/databeam",
  "crates/shared"
, "crates/providence"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
# panic = "abort"
panic = "unwind"
strip = true 
