[package]
name = "neospring"
version = "1.4.0"
edition = "2021"
authors = ["trisuaso", "swmff"]
description = "Ask, share, socialize!"
homepage = "https://neospring.org"
repository = "https://github.com/swmff/neospring"
license = "MIT"
rust-version = "1.80"

[features]
postgres = ["xsu-dataman/postgres", "xsu-authman/postgres"]
mysql = ["xsu-dataman/mysql", "xsu-authman/mysql"]
sqlite = ["xsu-dataman/sqlite", "xsu-authman/sqlite"]
default = ["xsu-dataman/sqlite", "xsu-authman/sqlite"]

[dependencies]
askama = { version = "0.12.1", features = ["with-axum"] }
askama_axum = "0.4.0"
axum = { version = "0.7.5", features = ["macros", "form"] }
axum-extra = { version = "0.9.3", features = ["cookie"] }
reqwest = { version = "0.12.5", features = ["json", "stream"] }
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
toml = "0.8.14"
tower-http = { version = "0.5.2", features = ["fs"] }
xsu-util = { path = "./xsu-util" }
xsu-dataman = { path = "./xsu-dataman", default-features = false }
xsu-authman = { path = "./xsu-authman", default-features = false }
# xsu-util = { path = "../xsu-util" }
# xsu-dataman = { path = "../xsu-dataman", default-features = false }
# xsu-authman = { path = "../xsu-authman", default-features = false }
serde_json = "1.0.120"
regex = "1.10.5"
mime_guess = "2.0.5"
hcaptcha = "2.4.6"
ammonia = "4.0.0"
futures-util = "0.3.30"
tokio-stream = "0.1.15"
futures = "0.3.30"
async-recursion = "1.1.1"

[[bin]]
path = "src/main.rs"
name = "neospring"
test = false
