id = "net.rainbeam.structs.Response"

[struct]
author = "net.rainbeam.structs.Profle"
question = "data.CitrusID"
content = "data.String"
id = "data.CitrusID"
tags = "data.Vec:String"
reply = "data.String"
context = "net.rainbeam.structs.Response.Context"
timestamp = "data.u128"
edited = "data.u128"
