[package]
name = "databeam"
version = "0.2.6"
edition = "2021"
description = "Database connection library"
authors = ["trisuaso", "swmff"]
homepage = "https://rainbeam.net"
repository = "https://github.com/swmff/rainbeam"
license = "MIT"

[features]
postgres = []
mysql = []
sqlite = []
default = ["sqlite"]

[dependencies]
redis = "0.27.6"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
toml = "0.8.19"
rainbeam-shared = "0.2.0"
pathbufd = "0.1.4"

[dependencies.sqlx]
version = "0.8.2"
features = [
    "sqlite",
    "postgres",
    "mysql",
    "any",
    "runtime-tokio",
    "tls-native-tls",
]
