port = 8080
secure = true
host = "https://example.com"
snowflake_server_id = 1234567890
blocked_hosts = ["https://example.com", "https://example2.com"]
media_dir = "./media"

name = "Rainbeam"
description = "My Rainbeam instance"

real_ip_header = "CF-Connecting-IP"
registration_enabled = true

[captcha]
# CHANGE THIS
site_key = "10000000-ffff-ffff-ffff-000000000001"
secret = "0x0000000000000000000000000000000000000000"
