[server]
name = "Neospring"   # put the instance name here
id = "neospring.org" # put the instance's domain here

[[schemas]]
id = "net.rainbeam.structs.Profile"
location = "schemas/structs/question.toml"

[[schemas]]
id = "net.rainbeam.structs.Profile.Metadata"
location = "schemas/structs/contexts/profile.toml"

[[schemas]]
id = "net.rainbeam.structs.Question"
location = "schemas/structs/question.toml"

[[schemas]]
id = "net.rainbeam.structs.Question.Context"
location = "schemas/structs/contexts/question.toml"

[[schemas]]
id = "net.rainbeam.structs.Response"
location = "schemas/structs/response.toml"

[[schemas]]
id = "net.rainbeam.structs.Response.Context"
location = "schemas/structs/contexts/response.toml"

[[schemas]]
id = "net.rainbeam.structs.Comment"
location = "schemas/structs/comment.toml"

[[schemas]]
id = "net.rainbeam.structs.Comment.Context"
location = "schemas/structs/contexts/comment.toml"

[[schemas]]
id = "net.rainbeam.structs.Mail"
location = "schemas/structs/contexts/mail.toml"
